export const BACKUP_LOADING = 'sync/BACKUP_LOADING'
export const BACKUP_SUCCESS = 'sync/BACKUP_SUCCESS'
export const BACKUP_FAIL = 'sync/BACKUP_FAIL'
export const LOGOUT = 'sync/LOGOUT'
export const TOKEN_LOADING = 'sync/TOKEN_LOADING'
export const TOKEN_LOAD_SUCCESS = 'sync/TOKEN_LOAD_SUCCESS'
export const TOKEN_LOAD_FAIL = 'sync/TOKEN_LOAD_FAIL'
export const RESTORE_LOADING = 'sync/RESTORE_LOADING'
export const RESTORE_SUCCESS = 'sync/RESTORE_SUCCESS'
export const RESTORE_FAIL = 'sync/RESTORE_FAIL'
export const UPDATE_BACKUP_DETAILS =
  'sync/UPDATE_BACKUP_DETAILS'
export const UPDATE_LOADING = 'sync/UPDATE_LOADING'
export const UPDATE_SUCCESS = 'sync/UPDATE_SUCCESS'
export const UPDATE_FAIL = 'sync/UPDATE_FAIL'
export const DISCONNECT = 'sync/DISCONNECT'
